import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { initFirebase } from '../src/config'
import { getAuth, signInWithEmailAndPassword, sendPasswordResetEmail } from "firebase/auth";
import { useEffect, useState } from 'react';
// import Link from 'next/link';
import Cookies from 'js-cookie';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  const [screen, changeScreen] = useState(true);
  var em = '';
  var pass = '';
  const app = initFirebase();
  const auth = getAuth();
  const [right, changeright] = useState(-900);
  const [right1, changeright1] = useState(-900);
  const [right2, changeright2] = useState(-900);


  return (

    <div className={styles.container}>
      <Head>
        <title>Work @ WGLLC</title>
        <meta name="application-name" content="Warriors Group Work" />
        <meta name="description" content="Generated by create next app" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Warriors Group LLC @work" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <div id="LoginPage">
          {screen ?
            <div id="maincont">
              <Image src='/pwatrans.png' width={300} height={300} alt='warriors logo' />
              <div id="head">Warriors Group LLC</div>
              <div id="subt">Login</div>
              <div className="subs">
                Enter your registered email
              </div>
              <input type="email" name="reg_email" id="em" className="inp" placeholder='Email' required
                onChange={() => {
                  em = document.getElementById("em").value;
                  changeright(-900)
                  changeright1(-900)
                  changeright2(-900)

                }} />

              <div className="subs">
                Enter your password
              </div>
              <input type="password" className="inp" placeholder='password' id='pass' required onChange={() => {
                pass = document.getElementById("pass").value;
                changeright(-900);
                changeright1(-900)
                changeright2(-900)

              }} />
              <div className="subs" id="forget" onClick={() => {
                changeScreen(false);
                console.log(auth);
              }}

              >Forgot password?</div>
              <div id="butt" onClick={
                function log() {
                  signInWithEmailAndPassword(auth, em, pass)
                    .then((userCred) => {
                      var user = userCred;
                      // console.log(user);
                      // console.log(auth.currentUser.displayName);
                      Cookies.set('isLogged', 'logged', { expires: 1 / 24 });
                      if (auth.currentUser.displayName == '' || auth.currentUser.email == '' || auth.currentUser.displayName == null || auth.currentUser.photoURL == null || auth.currentUser.photoURL == "") {

                        router.push('/updatedet')
                        console.log(auth.currentUser.displayName);
                      } else {

                        router.push('/dashboard')
                        console.log(auth.currentUser.displayName);
                      }

                      if (user.user.emailVerified == false) {
                        sendEmailVerification(auth.currentUser)
                          .then(() => {

                          });
                      }
                    }).catch((error) => {
                      var err = error.code;
                      var errmsg = error.message;
                      changeright(0);
                      changeright1(-900);
                      changeright2(-900);

                    })
                }
              } >Login</div>

            </div> : <div id="maincont">
              <Image src='/pwatrans.png' width={300} height={300} alt='warriors logo' />
              <div id="head">Warriors Group LLC</div>
              <div id="subt">Password Reset</div>
              <div className="subs">
                Enter your registered email
              </div>
              <input type="email" name="reg_email" id="em" className="inp" placeholder='Email'
                onChange={() => {
                  em = document.getElementById("em").value;

                  changeright1(-900);
                  changeright(-900);
                  changeright2(-900)


                }} />

              <div id="back" className="subs" onClick={() => {
                changeScreen(true)
              }}
              >Back to login</div>

              <div id="butt" onClick={
                async function reset() {
                  if (em != '') {
                    sendPasswordResetEmail(auth, em).then(() => {
                      changeright1(0);
                      console.log(screen);
                    })
                  } else {
                    changeright2(0);
                    console.log(screen);
                  }
                }
              } >Reset Password</div>


            </div>
          }




        </div>

        <div id="error" style={{ right: right }} >
          invalid email/password 😕 , Please try again
        </div>
        <div id="reset" style={{ right: right1 }} >
          Password reset link sent
        </div>
        <div id="noemail" style={{ right: right2 }} >
          Please enter your registered email in the email field
        </div>

      </main >


    </div >


  )







}
