import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { initFirebase } from '../src/config'
import { getAuth, signInWithEmailAndPassword, sendPasswordResetEmail } from "firebase/auth";
import { useEffect, useState } from 'react';
import Link from 'next/link';

export default function Home() {

  var em = '';
  var pass = '';
  const app = initFirebase();
  const auth = getAuth();
  const [right, changeright] = useState(-900);
  const [right1, changeright1] = useState(-900);
  const [right2, changeright2] = useState(-900);

  return (
    <div className={styles.container}>
      <Head>
        <title>Work @ WGLLC</title>
        <meta name="application-name" content="Warriors Group Work" />
        <meta name="description" content="Generated by create next app" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Warriors Group LLC @work" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="LoginPage">
          <div id="maincont">
            <Image src='/pwatrans.png' width={300} height={300} />
            <div id="head">Warriors Group LLC</div>
            <div id="subt">Login</div>
            <div className="subs">
              Enter your registered email
            </div>
            <input type="email" name="reg_email" id="em" className="inp" placeholder='Email'
              onChange={() => {
                em = document.getElementById("em").value;
                changeright(-900)
                changeright1(-900)
                changeright2(-900)

              }} />

            <div className="subs">
              Enter your password
            </div>
            <input type="text" className="inp" placeholder='password' id='pass' onChange={() => {
              pass = document.getElementById("pass").value;
              changeright(-900);
              changeright1(-900)
              changeright2(-900)

            }} />
            <Link href='/forgot'>  <div className="subs" id="forget"

            >Forgot password?</div></Link>
            <div id="butt" onClick={
              function log() {
                signInWithEmailAndPassword(auth, em, pass)
                  .then((userCred) => {
                    var user = userCred;
                    console.log(user);
                  }).catch((error) => {
                    var err = error.code;
                    var errmsg = error.message;
                    changeright(0);
                    changeright1(-900);
                    changeright2(-900);

                  })
              }
            } >Login</div>
         
          </div>
        </div>

        <div id="error" style={{ right: right }} >
          invalid email/password 😕 , Please try again
        </div>

      </main>


    </div>

  )
}
